### ISSUE TITLE
XML Names can start with an underscore

### ISSUE THREAD

**Issue by kddeisz** [SAP/xml-tools#102]
Copying from: https://github.com/prettier/plugin-xml/issues/56

```xml
<?xml version="1.0" encoding="utf-8" ?>
<a _test="5" />
```

The above should parse, but fails with a lexer error.

**Comment by bd82** [comment]
Yeah this seems like a mis-alignment with the spec.
- https://www.w3.org/TR/REC-xml/#NT-NameStartChar

**Comment by kddeisz** [comment]
It looks pretty close though! It looks like it's literally only missing the underscore.

**Comment by bd82** [comment]
https://github.com/SAP/xml-tools/pull/103

**Comment by bd82** [comment]
version 1.0.2 of @xml-tools/parser
