### ISSUE TITLE
Doesn't work in Firefox/Edge

### ISSUE THREAD

**Issue by cimak** [SAP/xml-tools#241]
FF/Edge does not support named capture groups in regex, my app is crashing at:
SyntaxError: invalid regexp group
https://github.com/SAP/xml-tools/blob/250169afda166eda6c38bb716c4233685adf32e3/packages/common/lib/xml-ns-key.js#L5

**Comment by bd82** [comment]
Hello @cimak  

The packages in this mono-repo are targeted for "modern" versions of node.js (10/12/14 currently).
**Not** towards browser usage.

Assuming (some of?) the packages could work in a browser env, e.g:
- No dependencies on node.js built in modules (fs/path/...).

Then you would need to compile (and bundle?) the sources to your desired ECMAScript version **yourself**.
Using relevant tools, e.g: Babel / Rollup / Parcel / Webpack.

Cheers.
Shahar.
