### ISSUE TITLE
Issue in latest publish of npm @xml-tools/parser@1.0.8?

### ISSUE THREAD

**Issue by rart** [SAP/xml-tools#286]
Hi, guys. I think there's been an error in publishing 1.0.8.

see https://unpkg.com/browse/@xml-tools/parser@1.0.8/lib/

Looks like somehow `lexer.js` & `parser.js` got removed from the published package.

I see they are still on the repo and the code still references them plus dependent projects fail when building ("unable to find ./parser.js`) so I suspect this is an error.

In my case, `@xml-tools/parser` is not a direct dependency of my project. I've temporarily added this to fix...
```json
"resolutions": {
  "@xml-tools/parser": "1.0.7"
}
```

**Comment by bd82** [comment]
Thanks.

I will have a look

**Comment by bd82** [comment]
Try 1.0.9

- https://unpkg.com/browse/@xml-tools/parser@1.0.9/lib/

**Comment by rart** [comment]
Looks good (build works, no deep tested anything else). Thanks for the quick fix! 👍🏻
