### ISSUE TITLE
Latest version(5.0.2) of @xml-tools/ast is broken

### ISSUE THREAD

**Issue by arajkumar** [SAP/xml-tools#287]
```
➜  /tmp npm i @xml-tools/ast@5.0.2
+ @xml-tools/ast@5.0.2
added 6 packages from 3 contributors and audited 6 packages in 1.773s
found 0 vulnerabilities

➜  /tmp ls node_modules/@xml-tools/ast/lib/
api.js
```

Directory `@xml-tools/ast/lib/` has api.js and rest of the files are missing.

CC: @bd82

**Comment by arajkumar** [comment]
It also evident from the npm registry that the size of 5.0.0 and 5.0.2 differs drastically.
https://www.npmjs.com/package/@xml-tools/ast/v/5.0.0
https://www.npmjs.com/package/@xml-tools/ast/v/5.0.2

**Comment by bd82** [comment]
Argh I missed fixing that package when I fixed the `files` section in all the other packages

**Comment by bd82** [comment]
Try 5.0.3
- https://unpkg.com/browse/@xml-tools/ast@5.0.3/lib/
