### ISSUE TITLE
Parsing attributes with < gives unexpected token

### ISSUE THREAD

**Issue by kddnewton** [SAP/xml-tools#383]
```xml
<?xml version="1.0" encoding="utf-8"?>
<test>
<a b="c<d" />
</test>
```

**Comment by voicis** [comment]
Looking at the [XML specification](https://www.w3.org/TR/xml/#ValueType) the `<` character is not allowed in attribute values and parsers should report this.

**Comment by kddnewton** [comment]
A-ha! Thanks. You can ignore this then.
